services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    networks:
      - backend
    volumes:
      # 配置文件 (使用项目内配置)
      - ./my.cnf:/etc/mysql/conf.d/my.cnf:ro
      # 数据持久化 (使用基础设施卷)
      - mysql_data:/var/lib/mysql
      # 日志 (使用基础设施卷)
      - app_logs:/data/log
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

networks:
  backend:
    external: true
    name: infra-backend

volumes:
  mysql_data:
    external: true
    name: infra_mysql_data
  app_logs:
    external: true
    name: infra_app_logs