# 网关服务 - Nginx 反向代理
services:
  nginx:
    image: nginx:1.27
    container_name: nginx
    networks:
      - frontend
      - backend
    restart: always
    ports:
      - "${NGINX_HTTP_PORT:-80}:80"
      - "${NGINX_HTTPS_PORT:-443}:443"
    volumes:
      # 基础配置文件
      - /home/www/workspace/infra/components/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/www/workspace/infra/components/nginx/conf.d:/etc/nginx/conf.d:ro
      # 日志
      - nginx_logs:/data/log/nginx
      # SSL 证书目录
      - /data/ssl:/data/ssl:ro
      # 应用配置目录（应用项目部署时复制配置文件到此目录）
      - /data/apps/nginx-configs:/etc/nginx/conf.d/apps:ro
      # Let's Encrypt 验证目录
      - /var/www/certbot:/var/www/certbot
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    ulimits:
      nofile: 100000
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    labels:
      - "infra.service=gateway"
      - "infra.category=network"

networks:
  frontend:
    external: true
    name: infra-frontend
  backend:
    external: true
    name: infra-backend

volumes:
  nginx_logs:
    external: true
    name: infra_nginx_logs