# 网关服务 - Nginx 反向代理
services:
  nginx:
    image: nginx:1.27
    container_name: nginx
    networks:
      - frontend
      - backend
    restart: always
    volumes:
      # Nginx 配置
      - /data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /data/nginx/conf.d:/etc/nginx/conf.d:ro
      # SSL 证书
      - /data/nginx/ssl:/etc/nginx/ssl:ro
      # 日志
      - nginx_logs:/data/log/nginx
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    ulimits:
      nofile: 100000
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    labels:
      - "infra.service=gateway"
      - "infra.category=network"

networks:
  frontend:
    external: true
    name: infra-frontend
  backend:
    external: true
    name: infra-backend

volumes:
  nginx_logs:
    external: true
    name: infra_nginx_logs