# 核心基础设施服务
# 包含网络定义和共享资源

networks:
  frontend:
    name: infra-frontend
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1
    driver_opts:
      com.docker.network.bridge.name: infra-frontend
      com.docker.network.bridge.enable_icc: "false"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.driver.mtu: "1500"
    labels:
      - "network.zone=public"
      - "network.access=external"
  
  backend:
    name: infra-backend
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
    driver_opts:
      com.docker.network.bridge.name: infra-backend
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.driver.mtu: "1500"
    labels:
      - "network.zone=private"
      - "network.access=internal"

# 共享卷定义 (使用 external 方式，由 Docker 自动创建)
volumes:
  # 数据持久化卷
  mysql_data:
    name: infra_mysql_data
  redis_data:
    name: infra_redis_data
  mongo_data:
    name: infra_mongo_data
  kafka_data:
    name: infra_kafka_data
  
  # 配置和日志卷
  jenkins_data:
    name: infra_jenkins_data
  nginx_logs:
    name: infra_nginx_logs
  app_logs:
    name: infra_app_logs