name: smoke
on: [workflow_dispatch]

jobs:
  ping:
    runs-on: [self-hosted, macOS, macmini]  # 用我们刚才的标签
    permissions:
      contents: read
    steps:
      - run: uname -a
      - run: sysctl -n machdep.cpu.brand_string || true
      - run: sw_vers
